### ISSUE TITLE
dynamic image size

### ISSUE THREAD

**Issue by ByteOtter** [ByteOtter/OtterDen#45]
Currently all uploaded images are resized to a hard coded resolution (800x600) when saved. And displayed in a fixed size resulting in a square.
I would like to keep the aspect ratio of uploaded images the same while fitting them into the post's frame. Meaning a 16:9 image should stay 16:9 etc.

**Comment by FruitFly638** [comment]
From my testing it seems like images already retain their aspect ratio, the thumbnail just shows a 300x300 version of the image.
A 4000x1000 Image gets turned into a 800x200 image for example

**Comment by ByteOtter** [comment]
> 

Ah, yes. Check `main.css` there should be `.article-img` which statically limits the size to 300x300.

**Comment by ByteOtter** [comment]
closed in #73
